#include "sourcebsp.h"

global const char *g_srcLumpNames[] = {
	"LUMP_ENTITIES",
	"LUMP_PLANES",
	"LUMP_TEXDATA",
	"LUMP_VERTEXES",
	"LUMP_VISIBILITY",
	"LUMP_NODES",
	"LUMP_TEXINFO",
	"LUMP_FACES",
	"LUMP_LIGHTING",
	"LUMP_OCCLUSION",
	"LUMP_LEAFS",
	"LUMP_FACEIDS",
	"LUMP_EDGES",
	"LUMP_SURFEDGES",
	"LUMP_MODELS",
	"LUMP_WORLDLIGHTS",
	"LUMP_LEAFFACES",
	"LUMP_LEAFBRUSHES",
	"LUMP_BRUSHES",
	"LUMP_BRUSHSIDES",
	"LUMP_AREAS",
	"LUMP_AREAPORTALS",
	"LUMP_FACEBRUSHES",
	"LUMP_FACEBRUSHLIST",
	"LUMP_UNUSED1",
	"LUMP_UNUSED2",
	"LUMP_DISPINFO",
	"LUMP_ORIGINALFACES",
	"LUMP_PHYSDISP",
	"LUMP_PHYSCOLLIDE",
	"LUMP_VERTNORMALS",
	"LUMP_VERTNORMALINDICES",
	"LUMP_DISP_LIGHTMAP_ALPHAS",
	"LUMP_DISP_VERTS",
	"LUMP_DISP_LIGHTMAP_SAMPLE_POSITIONS",
	"LUMP_GAME_LUMP",
	"LUMP_LEAFWATERDATA",
	"LUMP_PRIMITIVES",
	"LUMP_PRIMVERTS",
	"LUMP_PRIMINDICES",
	"LUMP_PAKFILE",
	"LUMP_CLIPPORTALVERTS",
	"LUMP_CUBEMAPS",
	"LUMP_TEXDATA_STRING_DATA",
	"LUMP_TEXDATA_STRING_TABLE",
	"LUMP_OVERLAYS",
	"LUMP_LEAFMINDISTTOWATER",
	"LUMP_FACE_MACRO_TEXTURE_INFO",
	"LUMP_DISP_TRIS",
	"LUMP_PROP_BLOB",
	"LUMP_WATEROVERLAYS",
	"LUMP_LEAF_AMBIENT_INDEX_HDR",
	"LUMP_LEAF_AMBIENT_INDEX",
	"LUMP_LIGHTING_HDR",
	"LUMP_WORLDLIGHTS_HDR",
	"LUMP_LEAF_AMBIENT_LIGHTING_HDR",
	"LUMP_LEAF_AMBIENT_LIGHTING",
	"LUMP_XZIPPAKFILE",
	"LUMP_FACES_HDR",
	"LUMP_MAP_FLAGS",
	"LUMP_OVERLAY_FADES",
	"LUMP_OVERLAY_SYSTEM_LEVELS",
	"LUMP_PHYSLEVEL",
	"LUMP_DISP_MULTIBLEND"
};

internal s32 SrcGetPlaneType(v3 normal)
{
	s32 type = -1;
	for (int i = 0; i < 3; i++)
	{
		if (normal[i] == 1.0f || normal[i] == -1.0f)
		{
			type = i;
			break;
		}
	}
	
	if (type == -1)
	{
		f32 x = HMM_ABS(normal.X);
		f32 y = HMM_ABS(normal.Y);
		f32 z = HMM_ABS(normal.Z);
		
		if (x >= y && x >= z)
		{
			type = SRC_PLANE_ANYX;
		}
		else if (y >= x && y >= z)
		{
			type = SRC_PLANE_ANYY;
		}
		else
		{
			type = SRC_PLANE_ANYZ;
		}
	}
	return type;
}
